---
- name: Check system time on Raspberry Pi
  hosts: 192.168.99.57
  gather_facts: no

  tasks:
    - name: Get current system time
      shell: ssh -o StrictHostKeyChecking=no -i {{ ansible_ssh_private_key_file }} pi@{{ ansible_host }} date
      register: current_time
      changed_when: false

    - name: Print current system time
      debug:
        msg: "Current system time: {{ current_time.stdout }}"
